spring:
  application:
    name: product-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component: Product Service

server:
  port: 9788
logging:
  level:
    root: debug
---
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    activate:
      on-profile: localhost
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: stock_management
  datasource:
      url: "jdbc:postgresql://localhost:5432/stock_management"
      username: postgres
      password: 112233

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

  client:
    service-url:
      default-zone: http://localhost:8761/eureka

---
spring:
  config:
    activate:
      on-profile: stage

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: stock_management
  datasource:
    url: "jdbc:postgresql://postgres:5432/stock_management"
    username: postgres
    password: 112233

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${random.uuid}

debug: false
