spring:
  application:
    name: zuul-edge-server

info:
  component: Zuul Edge Server


---


eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka    #http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

server:
  port: 8762
zuul:
  routes:
    product-service:
     path: /api/1.0/product/**
     service-id: product-service
     strip-prefix: false